package com.IDAO;

import java.util.ArrayList;
import java.util.Map;

import com.vo.Conofselcou;
import com.vo.Course;
import com.vo.Department;
import com.vo.Friend;
import com.vo.Major;
import com.vo.Notice;
import com.vo.Plan;
import com.vo.Student;
import com.vo.Stumess;
import com.vo.Suggestion;
import com.vo.Teacher;

public interface ISelectCoursesDAO {
	public abstract ArrayList<Notice> findAllNotice();
	public abstract String findSpecificNotice(String noticeID);
	public abstract ArrayList<Course> findAllCourses();
	public abstract ArrayList<Student> homepageQueryStudent(String querycontent);
	public abstract ArrayList<Teacher> homepageQueryTeacher(String querycontent);
	public abstract ArrayList<Course> homepageQueryCourse(String querycontent);
	public abstract ArrayList<Department> findALLDep();
	public abstract ArrayList<Major> findALLMaj();
	public abstract boolean Signin(Student stu);
	public abstract boolean login(String studentID,String password);
	public abstract ArrayList<Student> findStuInformation(String studentID);
	public abstract String findPassword(String studentID,String stuEmail);
	public abstract boolean changePassword(String sid,String oldpassword, String newpassword);
	public abstract ArrayList<Plan> findPlans(String major, String eduLevel);
	public abstract ArrayList<Course> findCoursesOfPlan(String planID);
	public abstract boolean adminLogin(String adminID,String password);
	public abstract String findAdminPassword(String adminID, String adminEmail);
	public abstract boolean changeAdminPs(String aid,String oldpassword, String newpassword);
	public abstract ArrayList<Plan> findAllPlans();
	public abstract boolean addPlan(String planID, String planName, String type,
			String majID, String degree, String eduLevel, String direction,
			short minCredit, String date);
	public abstract boolean updatePlan(Plan plan, String date);
	public abstract boolean deletePlan(String planid);
	public abstract boolean addcourse(Course cou);
	public abstract boolean updateCourse(Course cou);
	public abstract boolean deleteCourse(String courseid);
	public abstract ArrayList<Student> findAllStudnets();
	public abstract boolean deleteStudent(String studentid);
	public abstract boolean updateStudent(Student stu);
	public abstract boolean addTeacher(Teacher teacher);
	public abstract boolean updateTeacher(Teacher teacher);
	public abstract ArrayList<Teacher> findALLTeacher();
	public abstract boolean deleteTeacher(String teacherid);
	public abstract boolean addDep(Department depart);
	public abstract boolean updateDep(Department depart);
	public abstract boolean deleteDep(String depid);
	public abstract boolean addMaj(Major major);
	public abstract boolean deleteMaj(String majid);
	public abstract boolean updateMaj(Major major);
	public abstract boolean deleteNot(String notid);
	public abstract boolean addNotice(Notice notice);
	public abstract boolean updateNotice(Notice notice);
	public abstract ArrayList<Suggestion> adminFindAllSuggs();
	public abstract boolean studentSendSugg(Suggestion sugg);
	public abstract boolean deleteSugg(String suggid);
	public abstract ArrayList<Suggestion> searchSugg(String suggid);
	public abstract boolean replySugg(String replyContent, String replyTime, String suggestionID);
	public abstract ArrayList<Suggestion> checkReplySugg(String studentID);
	public abstract ArrayList<Course> findCoursebystu(String major, String grade, String eduLevel);
	public abstract boolean checkSeletced(String courseid, String studentID);
	public abstract boolean addCourseID(String conseID, String Courseid, String studentID, String pickuptime);
	public abstract boolean checkTime(String time, String studentID);
	public abstract Map<String, Short> findCurrentNum();
	public abstract boolean deleteCourseID(String courseid, String studentID);
	public abstract ArrayList<Conofselcou> checkSelected(String studentID);
	public abstract ArrayList<ArrayList<Conofselcou>> byTime();
	public abstract ArrayList<Conofselcou> findAllConse();
	public abstract boolean byRandom();
	public abstract ArrayList<Stumess> findAllMyMessage(String studentID);
	public abstract ArrayList<Friend> findAllMyFriend(String studentID);
	public abstract boolean deleteMess(String messageID);
	public abstract boolean addFriendRequest(String messageID, String fromid, String toid, String time);
	public abstract ArrayList<Stumess> findAllrequest(String studentID);
	public abstract boolean agreeToAdd(String messageID);
	public abstract boolean refuseToAdd(String messageID);
	public abstract Student findPersonnalMessage(String sID);
	public abstract ArrayList<Conofselcou> findPersonnalCourse(String sID);
	public abstract boolean deleteFriend(String beiID, String yaoID);
	public abstract boolean leaveMessage(String beiID, String yaoID, String mid, String time, String content);
	public abstract ArrayList<Stumess> findAllSPMyMessage(String beiID, String yaoID);
	public abstract boolean writeReply(String mid, String yaoID, String beiID, String time, String content);
	public abstract boolean upLoadImg(String sid, String location);
	public abstract boolean downloadCourseTable(String sid);
	public abstract boolean downloadConse();
}
